databases:
  - name: adiciona_aqui
    databaseName: adiciona_aqui
    user: adiciona_aqui
    plan: free

services:
  - type: web
    plan: free
    name: adiciona_aqui
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn adiciona_aqui.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: adiciona_aqui.settings.production
      - key: DATABASE_URL
        fromDatabase:
          name: adiciona_aqui
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
